name: ptw_ptp

on:
    push:
        branches: 
            [feature/*, fix/*, refactor/*, style/*, test/*]
    
    pull_request:
        types: [opened, synchronize]
        branches:
            - develop
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: ms_ptw_test
                    MYSQL_ROOT_PASSWORD: root 
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h localhost"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        strategy:
            matrix:
                php-version: ['8.3']

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.3
                extensions: json, dom, curl, libxml, mbstring
                coverage: none

            - name: Check PHP
              run: php -v

            - uses: actions/checkout@v2
            
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"

            - name: Copy phpstan
              run: php -r "file_exists('phpstan.neon') || copy('phpstan.neon', 'phpstan.neon');" 

            - name: run composer install
              run: composer install -n --prefer-dist

            - name: Wait for MySQL to be ready
              run: |
                echo "Waiting for MySQL to start..."
                for i in {1..30}; do
                  if mysqladmin ping -h 127.0.0.1 --silent; then
                    echo "MySQL is up and running!"
                    break
                  fi
                  echo "MySQL is not ready yet. Waiting..."
                  sleep 2
                done
              
            - name: Run Tests
              env:
                DB_CONNECTION: mysql
                DB_HOST: 127.0.0.1
                DB_PORT: 3306
                DB_DATABASE: ms_ptw_test
                DB_USERNAME: root
                DB_PASSWORD: ''
              run: php artisan test tests/Feature/UsersControllerTest.php

            - name: run npm install
              run: npm install 

            - name: Run laravel pint
              run: ./vendor/bin/pint

            - name: Run laravel phpstan
              run: ./vendor/bin/phpstan analyse

            - name: Run script
              run: |
                echo "Hola mundo"
                ls
                echo "Fin"
